language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
node_js:
  - "node"
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install -g bower
  - bower install jquery --config.directory=.
deploy:
  provider: pages
  github-token: $GH_PAGES_TOKEN
  skip-cleanup: true
  keep-history: true
  verbose: true
  on:
    branch: master