language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
node_js:
  - "node"
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
  - polymer install
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build/es6-unbundled
  github-token: $GH_PAGES_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master